<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\AtlanticDivision.png" />
    <None Remove="Assets\CentralDivision.png" />
    <None Remove="Assets\EasternConference.gif" />
    <None Remove="Assets\GreenExitArrowRight.jpg" />
    <None Remove="Assets\MetropolitanDivision.png" />
    <None Remove="Assets\NhlLeague.gif" />
    <None Remove="Assets\PacificDivision.png" />
    <None Remove="Assets\WesternConference.gif" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.2.0" />
    <PackageReference Include="telerik.ui.for.wpf.60.xaml" Version="2024.3.821" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\AtlanticDivision.png" />
    <Resource Include="Assets\ColoradoAvalanche.gif" />
    <Resource Include="Assets\ChicagoBlackhawks.gif" />
    <Resource Include="Assets\ColumbusBlueJackets.gif" />
    <Resource Include="Assets\GreenExitArrowRight.jpg" />
    <Resource Include="Assets\DefaultLogo.gif" />
    <Resource Include="Assets\StLouisBlues.gif" />
    <Resource Include="Assets\BostonBruins.gif" />
    <Resource Include="Assets\MontrealCanadiens.gif" />
    <Resource Include="Assets\VancouverCanucks.gif" />
    <Resource Include="Assets\WashingtonCapitals.gif" />
    <Resource Include="Assets\CentralDivision.png" />
    <Resource Include="Assets\NewJerseyDevils.gif" />
    <Resource Include="Assets\AnaheimDucks.gif" />
    <Resource Include="Assets\EasternConference.gif" />
    <Resource Include="Assets\CalgaryFlames.gif" />
    <Resource Include="Assets\PhiladelphiaFlyers.gif" />
    <Resource Include="Assets\VegasGoldenKnights.gif" />
    <Resource Include="Assets\UtahHockeyClub.gif" />
    <Resource Include="Assets\CarolinaHurricanes.gif" />
    <Resource Include="Assets\NewYorkIslanders.gif" />
    <Resource Include="Assets\WinnipegJets.gif" />
    <Resource Include="Assets\LosAngelesKings.gif" />
    <Resource Include="Assets\SeattleKraken.gif" />
    <Resource Include="Assets\TorontoMapleLeafs.gif" />
    <Resource Include="Assets\TampaBayLightning.gif" />
    <Resource Include="Assets\MetropolitanDivision.png" />
    <Resource Include="Assets\NhlLeague.gif" />
    <Resource Include="Assets\EdmontonOilers.gif" />
    <Resource Include="Assets\PacificDivision.png" />
    <Resource Include="Assets\FloridaPanthers.gif" />
    <Resource Include="Assets\PittsburghPenguins.gif" />
    <Resource Include="Assets\NashvillePredators.gif" />
    <Resource Include="Assets\NewYorkRangers.gif" />
    <Resource Include="Assets\DetroitRedWings.gif" />
    <Resource Include="Assets\BuffaloSabres.gif" />
    <Resource Include="Assets\OttawaSenators.gif" />
    <Resource Include="Assets\SanJoseSharks.gif" />
    <Resource Include="Assets\DallasStars.gif" />
    <Resource Include="Assets\WesternConference.gif" />
    <Resource Include="Assets\MinnesotaWild.gif" />
  </ItemGroup>

</Project>
